### GET ALL RAW
GET http://localhost:3000/articles?raw=true

### GET ALL PROCESSED
GET http://localhost:3000/articles

### GET BY ID
GET http://localhost:3000/articles/8602a9aa-6fe1-4c84-a415-876a31047c34

### GET BY CATEGORY
GET http://localhost:3000/articles/categories/poo

### POST
POST http://localhost:3000/articles
Content-Type: application/json

{
  "id-all": 43,
  "name": "Termo stanley",
  "price": 254.00,
  "category_id": 1,
  "description": "Mantiene el agua fría por 10 horas",
  "brand_id": 1,
  "availability": true,
  "release_date": "1969-10-01"
}

### DELETE
DELETE http://localhost:3000/articles/6aaec538-8906-48cf-b0a6-98824beb24cc

### PATCH
PATCH http://localhost:3000/articles/494079db-f1a3-416a-8043-462529107d18
Content-Type: application/json

{
  "price": 25,
  "category": 1
}

